### ISSUE TITLE
Associated URL 404s

### ISSUE THREAD

**Issue by trn1ty** [ctrlaltdev/LMGTFY-queries#4]
as of 2019-01-21 https://ctrlaltdev.xyz/LMGTFY-queries 404s

**Comment by ctrlaltdev** [comment]
Thanks for the info!
I've updated the link to the correct one now: https://ctrlaltdev.xyz/LMGTFY

**Comment by trn1ty** [comment]
![image](https://user-images.githubusercontent.com/26193059/51503617-e890e800-1da9-11e9-9175-e349dfe3a3d0.png)
(edit: above image is supposed to be a 404; the hosting site isn't broken)
Sorry, mate, looks like it still 404s. Maybe it's my machine or something

**Comment by ctrlaltdev** [comment]
@RandomGuyDTB Nope, not you - I just cleared the cache and got it too.
I think my netlify is not confed correctly to handle react router.

I'll fix it later today.

**Comment by ctrlaltdev** [comment]
I actually rushed a deploy with a fix - tell me if the link works for you now.

**Comment by trn1ty** [comment]
Yep, works fine now.

**Comment by ctrlaltdev** [comment]
Cool, thanks again for creating an issue for that.

**Comment by trn1ty** [comment]
Nah, you deserve the thanks for fixing it
